/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const UserProfile = IDL.Record({
  'displayName' : IDL.Text,
  'lastSeen' : Timestamp,
  'online' : IDL.Bool,
});
export const ConversationId = IDL.Text;
export const MessageId = IDL.Nat;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const FileAttachment = IDL.Record({
  'blob' : ExternalBlob,
  'name' : IDL.Text,
});
export const UserId = IDL.Principal;
export const Message = IDL.Record({
  'id' : MessageId,
  'content' : IDL.Text,
  'file' : IDL.Opt(FileAttachment),
  'sender' : UserId,
  'timestamp' : Timestamp,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerProfile' : IDL.Func([], [UserProfile], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMessages' : IDL.Func([ConversationId], [IDL.Vec(Message)], ['query']),
  'getOrCreateConversation' : IDL.Func([UserId], [ConversationId], []),
  'getTypingParticipants' : IDL.Func(
      [ConversationId],
      [IDL.Text, IDL.Vec(UserId)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerOrUpdateProfile' : IDL.Func([IDL.Text], [], []),
  'sendMessage' : IDL.Func(
      [ConversationId, IDL.Text, IDL.Opt(FileAttachment)],
      [MessageId],
      [],
    ),
  'setTyping' : IDL.Func([ConversationId, IDL.Bool], [], []),
  'updateLastSeen' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const UserProfile = IDL.Record({
    'displayName' : IDL.Text,
    'lastSeen' : Timestamp,
    'online' : IDL.Bool,
  });
  const ConversationId = IDL.Text;
  const MessageId = IDL.Nat;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const FileAttachment = IDL.Record({
    'blob' : ExternalBlob,
    'name' : IDL.Text,
  });
  const UserId = IDL.Principal;
  const Message = IDL.Record({
    'id' : MessageId,
    'content' : IDL.Text,
    'file' : IDL.Opt(FileAttachment),
    'sender' : UserId,
    'timestamp' : Timestamp,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerProfile' : IDL.Func([], [UserProfile], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMessages' : IDL.Func([ConversationId], [IDL.Vec(Message)], ['query']),
    'getOrCreateConversation' : IDL.Func([UserId], [ConversationId], []),
    'getTypingParticipants' : IDL.Func(
        [ConversationId],
        [IDL.Text, IDL.Vec(UserId)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerOrUpdateProfile' : IDL.Func([IDL.Text], [], []),
    'sendMessage' : IDL.Func(
        [ConversationId, IDL.Text, IDL.Opt(FileAttachment)],
        [MessageId],
        [],
      ),
    'setTyping' : IDL.Func([ConversationId, IDL.Bool], [], []),
    'updateLastSeen' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };